envVarGroups:
  - name: spree-envs
    envVars:
      - key: DB_POOL
        value: 10

databases:
  - name: spree-db
    databaseName: spree
    user: spree
    plan: free # Changed to free tier

services:
  - type: web
    name: spree-web
    runtime: ruby
    plan: free # Changed to free tier
    buildCommand: bin/render-build.sh
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spree-db
          property: connectionString
      - key: SECRET_KEY_BASE
        sync: false
      - key: WEB_CONCURRENCY
        value: 1 # Reduced for free tier
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: keyvalue
          property: connectionString
  - type: worker
    name: spree-worker
    runtime: ruby
    plan: free # Changed to free tier
    buildCommand: bin/render-build.sh
    startCommand: bundle exec sidekiq
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spree-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: keyvalue
          property: connectionString
      - key: SECRET_KEY_BASE
        sync: false
      - key: REDIS_CACHE_URL
        fromService:
          type: keyvalue
          name: keyvalue-cache
          property: connectionString
      - fromGroup: spree-envs
  
  - type: keyvalue
    name: keyvalue
    ipAllowList: []
    plan: free # Changed to free tier
    maxmemoryPolicy: noeviction

  - type: keyvalue
    name: keyvalue-cache
    ipAllowList: []
    plan: free # Changed to free tier
    maxmemoryPolicy: allkeys-lru